events {}

http {
    upstream api_stable {
        server api:8000;
    }

    upstream api_canary {
        server api_canary:8000;
    }

    split_clients "$remote_addr" $sentiment_backend {
        5% api_canary;
        * api_stable;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://$sentiment_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}